### ISSUE TITLE
提示 Trying to access array offset on value of type bool 错误

### ISSUE THREAD

**Issue by yxue2020** [freyo/flysystem-qcloud-cos-v5#56]
提示 Trying to access array offset on value of type bool 错误

- "laravel/framework": "^8.75",
- "freyo/flysystem-qcloud-cos-v5": "^2.2",

```
ErrorException: Trying to access array offset on value of type bool in file vendor/qcloud/cos-sdk-v5/src/Signature.php on line 99

#0 vendor/qcloud/cos-sdk-v5/src/Signature.php(99): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Trying to acces...', '/Users/chao/w14...', 99, Array)
#1 vendor/qcloud/cos-sdk-v5/src/Signature.php(64): Qcloud\Cos\Signature->createAuthorization(Object(GuzzleHttp\Psr7\Request))
#2 vendor/qcloud/cos-sdk-v5/src/SignatureMiddleware.php(21): Qcloud\Cos\Signature->signRequest(Object(GuzzleHttp\Psr7\Request))
#3 vendor/guzzlehttp/guzzle/src/Middleware.php(240): Qcloud\Cos\SignatureMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#4 vendor/guzzlehttp/guzzle/src/RetryMiddleware.php(67): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#5 vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(64): GuzzleHttp\RetryMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#6 vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#7 vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(55): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#8 vendor/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#9 vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#10 vendor/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#11 vendor/guzzlehttp/guzzle/src/Client.php(107): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#12 vendor/guzzlehttp/command/src/ServiceClient.php(173): GuzzleHttp\Client->sendAsync(Object(GuzzleHttp\Psr7\Request), Array)
#13 [internal function]: GuzzleHttp\Command\ServiceClient->GuzzleHttp\Command\{closure}()
#14 vendor/guzzlehttp/promises/src/Coroutine.php(71): Generator->current()
#15 vendor/guzzlehttp/promises/src/Coroutine.php(86): GuzzleHttp\Promise\Coroutine->__construct(Object(Closure))
#16 vendor/guzzlehttp/promises/src/functions.php(362): GuzzleHttp\Promise\Coroutine::of(Object(Closure))
#17 vendor/guzzlehttp/command/src/ServiceClient.php(181): GuzzleHttp\Promise\coroutine(Object(Closure))
#18 vendor/guzzlehttp/guzzle-services/src/Handler/ValidatedDescriptionHandler.php(79): GuzzleHttp\Command\ServiceClient->GuzzleHttp\Command\{closure}(Object(GuzzleHttp\Command\Command))
#19 vendor/guzzlehttp/command/src/ServiceClient.php(85): GuzzleHttp\Command\Guzzle\Handler\ValidatedDescriptionHandler->GuzzleHttp\Command\Guzzle\Handler\{closure}(Object(GuzzleHttp\Command\Command))
#20 vendor/guzzlehttp/command/src/ServiceClient.php(77): GuzzleHttp\Command\ServiceClient->executeAsync(Object(GuzzleHttp\Command\Command))
#21 vendor/guzzlehttp/command/src/ServiceClient.php(153): GuzzleHttp\Command\ServiceClient->execute(Object(GuzzleHttp\Command\Command))
#22 vendor/qcloud/cos-sdk-v5/src/Client.php(296): GuzzleHttp\Command\ServiceClient->__call('PutObject', Array)
#23 vendor/qcloud/cos-sdk-v5/src/Client.php(348): Qcloud\Cos\Client->__call('putObject', Array)
```

**Comment by yxue2020** [comment]
配置文件内容 config/filesystems.php

```php
        'cosv5' => [
            'driver' => 'cosv5',
            'region' =>  env('COSV5_REGION', 'ap-guangzhou'),
            'credentials' => [
                'appId' => env('COSV5_APP_ID', '*********'),
                'secretId' =>  env('COSV5_SECRET_ID', '*********'),
                'secretKey' => env('COSV5_SECRET_KEY', '*********'),
            ],
            'cdn' => '',
            'scheme' => env('COSV5_SCHEME', 'https'),
            'bucket' => env('COSV5_BUCKET', '*********'),
            'read_from_cdn'   => env('COSV5_READ_FROM_CDN', false),
            'cdn_key'         => env('COSV5_CDN_KEY'),
            'encrypt'         => env('COSV5_ENCRYPT', false),
        ],
```

**Comment by yxue2020** [comment]
update "qcloud/cos-sdk-v5": "^2.5",
